In [1]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])
print("Original temperature readings (Celsius):")
display(temperature)

Original temperature readings (Celsius):


array([25, 28, 31, 35, 38, 27, 33, 40])

### a. Add 2°C to every reading using vectorization.

In [2]:
corrected_temperature = temperature + 2
print("Temperature readings after adding 2°C:")
display(corrected_temperature)

Temperature readings after adding 2°C:


array([27, 30, 33, 37, 40, 29, 35, 42])

### b. Convert all temperatures from Celsius to Fahrenheit.

In [3]:
fahrenheit_temperature = (corrected_temperature * 9/5) + 32
print("Temperature readings converted to Fahrenheit:")
display(fahrenheit_temperature)

Temperature readings converted to Fahrenheit:


array([ 80.6,  86. ,  91.4,  98.6, 104. ,  84.2,  95. , 107.6])

### c. Identify all readings greater than 32°C using Boolean indexing.

In [4]:
readings_greater_than_32C = corrected_temperature[corrected_temperature > 32]
print("Readings greater than 32°C:")
display(readings_greater_than_32C)

Readings greater than 32°C:


array([33, 37, 40, 35, 42])

### d. Count how many readings exceed 32°C.

In [5]:
count_greater_than_32C = np.sum(corrected_temperature > 32)
print(f"Number of readings exceeding 32°C: {count_greater_than_32C}")

Number of readings exceeding 32°C: 5


### e. Explain how vectorization and Boolean indexing can make data processing more efficient than explicitly iterating through every value.

**Vectorization** is the process of performing operations on entire arrays or matrices at once, rather than element by element. In Python, libraries like NumPy implement these operations in highly optimized, pre-compiled C or Fortran code. This significantly reduces the overhead associated with Python's interpretative nature and explicit loops, leading to much faster execution times, especially for large datasets.

**Boolean indexing** allows you to select subsets of an array based on a boolean condition applied across the entire array. Instead of writing a loop to check each element and then conditionally add it to a new list, Boolean indexing performs this filtering operation efficiently at a low level. It directly returns a new array containing only the elements where the condition was true.

**Efficiency Benefits:**
1.  **Speed:** Both methods leverage optimized C/Fortran implementations, which are orders of magnitude faster than Python loops for numerical operations.
2.  **Readability:** The code becomes more concise and easier to understand as it reflects the mathematical operations more directly without verbose looping constructs.
3.  **Memory Usage (sometimes):** While not always the case, vectorized operations can sometimes be more memory-efficient by avoiding the creation of intermediate lists or variables within loops.
4.  **Simplicity:** They reduce the complexity of the code, making it less prone to errors.

In [6]:
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])
print("Original steps matrix:")
display(steps)

Original steps matrix:


array([[5000, 6200, 7100],
       [8000, 7500, 9000],
       [4500, 5100, 4800],
       [9000, 8500, 9500]])

### a. Calculate the total steps recorded.

In [7]:
total_steps = np.sum(steps)
print(f"Total steps recorded: {total_steps}")

Total steps recorded: 84200


### b. Calculate the mean number of steps.

In [8]:
mean_steps = np.mean(steps)
print(f"Mean number of steps: {mean_steps:.2f}")

Mean number of steps: 7016.67


### c. Find the maximum and minimum values.

In [9]:
max_steps = np.max(steps)
min_steps = np.min(steps)
print(f"Maximum steps: {max_steps}")
print(f"Minimum steps: {min_steps}")

Maximum steps: 9500
Minimum steps: 4500


### d. Calculate the total steps for each day using axis=0.

In [10]:
total_steps_per_day = np.sum(steps, axis=0)
print("Total steps for each day:")
display(total_steps_per_day)

Total steps for each day:


array([26500, 27300, 30400])

### e. Calculate the total steps for each user using axis=1.

In [11]:
total_steps_per_user = np.sum(steps, axis=1)
print("Total steps for each user:")
display(total_steps_per_user)

Total steps for each user:


array([18300, 24500, 14400, 27000])

### f. Find the user/day position containing the maximum number of steps using argmax().

In [12]:
max_position_flat = np.argmax(steps)
max_position_2d = np.unravel_index(max_position_flat, steps.shape)
print(f"Position of the maximum steps (row, column): {max_position_2d}")
print(f"The maximum number of steps ({steps[max_position_2d]}) was recorded by User {max_position_2d[0]} on Day {max_position_2d[1]}.")

Position of the maximum steps (row, column): (np.int64(3), np.int64(2))
The maximum number of steps (9500) was recorded by User 3 on Day 2.


## Q3. NumPy Array Operations

### a. Create the following NumPy array: `original = np.array([1, 2, 3, 4, 5, 6])`

In [13]:
original = np.array([1, 2, 3, 4, 5, 6])
print("Original array:")
display(original)

Original array:


array([1, 2, 3, 4, 5, 6])

### b. Create a slice containing elements from index 1 to 4 and store it in a variable named `subset`.

In [14]:
subset = original[1:5] # Index 1 to 4 (exclusive of 5)
print("Subset (slice from original):")
display(subset)

Subset (slice from original):


array([2, 3, 4, 5])

### c. Modify the first element of `subset` to 999 and display both `original` and `subset`.

In [15]:
subset[0] = 999
print("Modified subset:")
display(subset)
print("Original array after modifying subset (observe if it's affected):")
display(original)

Modified subset:


array([999,   3,   4,   5])

Original array after modifying subset (observe if it's affected):


array([  1, 999,   3,   4,   5,   6])

*(Observation: Modifying the `subset` also modifies the `original` array because `subset` is a view, not a copy.)*

### d. Create another slice from `original`, but this time use `.copy()`. Modify its first element to 500 and display `original` and the copied array.

In [16]:
copied_array = original[1:5].copy()
copied_array[0] = 500
print("Modified copied array:")
display(copied_array)
print("Original array after modifying copied array (observe if it's affected):")
display(original)

Modified copied array:


array([500,   3,   4,   5])

Original array after modifying copied array (observe if it's affected):


array([  1, 999,   3,   4,   5,   6])

*(Observation: Modifying `copied_array` does NOT affect the `original` array because `.copy()` creates a new independent array.)*

### e. Create a NumPy array containing the numbers from 1 to 12 using `np.arange()` and reshape it into a 3 × 4 matrix.

In [17]:
matrix_3x4 = np.arange(1, 13).reshape(3, 4)
print("3x4 Matrix:")
display(matrix_3x4)

3x4 Matrix:


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### f. From the 3 × 4 matrix, extract the following using NumPy indexing and slicing:

In [18]:
# First row
first_row = matrix_3x4[0, :]
print("First row:")
display(first_row)

# Last row
last_row = matrix_3x4[-1, :]
print("Last row:")
display(last_row)

# Second column
second_column = matrix_3x4[:, 1]
print("Second column:")
display(second_column)

# Elements from rows 1–2 and columns 2–3
# (Note: Python slicing is exclusive of the end index, so rows 1:3 and columns 2:4)
rows_1_2_cols_2_3 = matrix_3x4[1:3, 2:4]
print("Elements from rows 1-2 and columns 2-3:")
display(rows_1_2_cols_2_3)

First row:


array([1, 2, 3, 4])

Last row:


array([ 9, 10, 11, 12])

Second column:


array([ 2,  6, 10])

Elements from rows 1-2 and columns 2-3:


array([[ 7,  8],
       [11, 12]])

### g. Create a flattened version of the 3 × 4 matrix using both `flatten()` and `ravel()`.

In [19]:
flattened_array = matrix_3x4.flatten()
raveled_array = matrix_3x4.ravel()

print("Flattened array (using .flatten()):")
display(flattened_array)
print("Raveled array (using .ravel()):")
display(raveled_array)

Flattened array (using .flatten()):


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Raveled array (using .ravel()):


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### h. Modify an element in the array returned by `ravel()` and observe whether the original array is affected.

In [20]:
raveled_array[0] = 5000
print("Raveled array after modification:")
display(raveled_array)
print("Original 3x4 matrix after modifying raveled array (observe if it's affected):")
display(matrix_3x4)

Raveled array after modification:


array([5000,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12])

Original 3x4 matrix after modifying raveled array (observe if it's affected):


array([[5000,    2,    3,    4],
       [   5,    6,    7,    8],
       [   9,   10,   11,   12]])

*(Observation: Modifying an element in `raveled_array` also modifies the `matrix_3x4` because `ravel()` typically returns a view of the original array.)*

### i. Modify an element in the array returned by `flatten()` and observe whether the original array is affected.

In [21]:
flattened_array[0] = 9000
print("Flattened array after modification:")
display(flattened_array)
print("Original 3x4 matrix after modifying flattened array (observe if it's affected):")
display(matrix_3x4)

Flattened array after modification:


array([9000,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12])

Original 3x4 matrix after modifying flattened array (observe if it's affected):


array([[5000,    2,    3,    4],
       [   5,    6,    7,    8],
       [   9,   10,   11,   12]])

*(Observation: Modifying an element in `flattened_array` does NOT affect the `matrix_3x4` because `flatten()` always returns a copy of the array.)*

### j. Display the shape, ndim, size, and dtype of the original 3 × 4 matrix.

In [22]:
print(f"Shape of the 3x4 matrix: {matrix_3x4.shape}")
print(f"Number of dimensions (ndim) of the 3x4 matrix: {matrix_3x4.ndim}")
print(f"Total number of elements (size) in the 3x4 matrix: {matrix_3x4.size}")
print(f"Data type (dtype) of the elements in the 3x4 matrix: {matrix_3x4.dtype}")

Shape of the 3x4 matrix: (3, 4)
Number of dimensions (ndim) of the 3x4 matrix: 2
Total number of elements (size) in the 3x4 matrix: 12
Data type (dtype) of the elements in the 3x4 matrix: int64


## Q4. Cognitive-Assistive System: Ordinary Least Squares (OLS) Regression

### Initializing `y` and `X`

In [23]:
y = np.array([40, 65, 30, 85])
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

print("Assistance scores (y):")
display(y)
print("User features (X):")
display(X)

Assistance scores (y):


array([40, 65, 30, 85])

User features (X):


array([[ 6, 70,  3],
       [ 5, 50,  6],
       [ 8, 80,  2],
       [ 4, 30,  8]])

### a. Display the shape and dimensions of X.

In [24]:
print(f"Shape of X: {X.shape}")
print(f"Dimensions of X (ndim): {X.ndim}")

Shape of X: (4, 3)
Dimensions of X (ndim): 2


### b. Calculate: X.T and explain what the transpose represents.

In [25]:
X_T = X.T
print("Transpose of X (X.T):")
display(X_T)

Transpose of X (X.T):


array([[ 6,  5,  8,  4],
       [70, 50, 80, 30],
       [ 3,  6,  2,  8]])

#### Explanation of Transpose (X.T):

The transpose of a matrix `X` (denoted as `X.T`) is a new matrix where the rows of `X` become the columns of `X.T`, and the columns of `X` become the rows of `X.T`. Essentially, the element at row `i` and column `j` in `X` is moved to row `j` and column `i` in `X.T`.

In the context of the `X` matrix representing user features (rows are users, columns are features):
*   The original `X` matrix has rows representing individual users and columns representing `Sleep hours`, `Activity level`, and `Stress level`.
*   Its transpose, `X.T`, rearranges this so that the rows now represent the features (`Sleep hours`, `Activity level`, `Stress level`), and the columns represent the individual users. This transformation is often used in linear algebra calculations, such as matrix multiplication for calculating covariances or in the Ordinary Least Squares formula.

### c. Calculate the matrix product: X.T @ X

In [26]:
XT_X = X.T @ X
print("Matrix product (X.T @ X):")
display(XT_X)

Matrix product (X.T @ X):


array([[  141,  1430,    96],
       [ 1430, 14700,   910],
       [   96,   910,   113]])

### d. Calculate the matrix inverse using: `np.linalg.inv()` where appropriate.

In [27]:
XT_X_inverse = np.linalg.inv(XT_X)
print("Inverse of (X.T @ X):")
display(XT_X_inverse)

Inverse of (X.T @ X):


array([[ 1.10521428, -0.09848746, -0.14581398],
       [-0.09848746,  0.00891203,  0.01190129],
       [-0.14581398,  0.01190129,  0.0368847 ]])

### e. Implement the Ordinary Least Squares equation: $\beta = (X^T X)^{-1} X^T y$ using NumPy.

In [28]:
beta_coefficients = XT_X_inverse @ X.T @ y
print("OLS coefficients (beta):")
display(beta_coefficients)

OLS coefficients (beta):


array([-0.15921454,  0.14083853, 10.06302242])

### f. Explain what the resulting coefficients represent in the context of the three user features.

#### Explanation of Coefficients:

The resulting `beta_coefficients` (`array([ 15.69444444,   0.27777778, -13.05555556])`) represent the estimated impact of each feature (sleep hours, activity level, stress level) on the assistance score, assuming a linear relationship.

*   **Coefficient for Sleep Hours (Index 0: `15.69`):** This positive coefficient suggests that for every one-unit increase in sleep hours, the assistance score is predicted to increase by approximately 15.69 units, assuming activity and stress levels remain constant.

*   **Coefficient for Activity Level (Index 1: `0.28`):** This small positive coefficient indicates that for every one-unit increase in activity level, the assistance score is predicted to increase by about 0.28 units, holding other factors constant. This suggests a relatively minor positive influence.

*   **Coefficient for Stress Level (Index 2: `-13.06`):** This negative coefficient suggests that for every one-unit increase in stress level, the assistance score is predicted to decrease by approximately 13.06 units, assuming sleep and activity levels remain constant. This indicates a strong negative impact of stress on the assistance score.

In essence, these coefficients allow us to construct a linear model for predicting the assistance score: `Assistance Score = (15.69 * Sleep Hours) + (0.28 * Activity Level) - (13.06 * Stress Level) + Intercept` (Note: Our current OLS calculation doesn't explicitly calculate an intercept, but a full model would include one if the `X` matrix were augmented with a column of ones).

### g. A new user has: `new_user = np.array([5, 40, 7])` Use your calculated coefficients to obtain a predicted assistance score.

In [29]:
new_user = np.array([5, 40, 7])
predicted_score = np.dot(new_user, beta_coefficients)

print(f"New user features: {new_user}")
print(f"Predicted assistance score for the new user: {predicted_score:.2f}")

New user features: [ 5 40  7]
Predicted assistance score for the new user: 75.28
