In [1]:
import numpy as np

### Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

arr_add_2 = arr_1d + 2
print(arr_add_2)

arr_mul_3 = arr_1d * 3
print(arr_mul_3)

arr_div_2 = arr_1d / 2
print(arr_div_2)

[1 2 3 4 5]
[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


### Q.2 Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [3]:
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print(arr)
print(reversed_arr)

from collections import Counter

def most_frequent_value_and_indices(arr):
    counts = Counter(arr)
    if not counts:
        return "Array is empty", []
    most_common_value = counts.most_common(1)[0][0]
    indices = np.where(arr == most_common_value)[0]
    return most_common_value, indices

x = np.array([1,2,3,4,5,1,2,1,1,1])
most_freq_x, indices_x = most_frequent_value_and_indices(x)
print(f"\nArray x: {x}")
print(f"Most frequent value in x: {most_freq_x}")
print(f"Indices of most frequent value in x: {list(indices_x)}")

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
most_freq_y, indices_y = most_frequent_value_and_indices(y)
print(f"\nArray y: {y}")
print(f"Most frequent value in y: {most_freq_y}")
print(f"Indices of most frequent value in y: {list(indices_y)}")

[1 2 3 6 4 5]
[5 4 6 3 2 1]

Array x: [1 2 3 4 5 1 2 1 1 1]
Most frequent value in x: 1
Indices of most frequent value in x: [np.int64(0), np.int64(5), np.int64(7), np.int64(8), np.int64(9)]

Array y: [1 1 1 2 3 4 2 4 3 3]
Most frequent value in y: 1
Indices of most frequent value in y: [np.int64(0), np.int64(1), np.int64(2)]


### Q.3 For the given 2-D array arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]]), access elements using row and column indices as follows:
a) Access 1st row, 2nd column

b) Access 3rd row, 1st column

In [4]:
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])
print(arr_2d)
element_1_2 = arr_2d[0, 1]
print(element_1_2)

element_3_1 = arr_2d[2, 0]
print(element_3_1)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
20
70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?


### Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute?

In [6]:
a_array = np.linspace(10, 100, 25)
print(a_array)

print(f"\nDimensions: {a_array.ndim}")
print(f"Shape: {a_array.shape}")
print(f"Total elements: {a_array.size}")
print(f"Data type: {a_array.dtype}")
print(f"Total number of bytes: {a_array.nbytes} bytes")

reshaped_for_transpose = a_array.reshape(-1, 1)
transposed_by_reshape = reshaped_for_transpose.T
print(f"\nOriginal 1D array reshaped to a column vector (shape {reshaped_for_transpose.shape}):\n{reshaped_for_transpose}")
print(f"Transpose using reshape() and .T (shape {transposed_by_reshape.shape}):\n{transposed_by_reshape}")

transposed_by_T_1d = a_array.T
print(f"\nTranspose of 1D array using .T (shape {transposed_by_T_1d.shape}):\n{transposed_by_T_1d}")
print(f"Is my_linspace_array == transposed_by_T_1d: {np.array_equal(a_array, transposed_by_T_1d)}")

row_vector = a_array.reshape(1, -1)
transposed_row_vector = row_vector.T
print(f"\nOriginal array reshaped to a row vector (shape {row_vector.shape}):\n{row_vector}")
print(f"Transpose of row vector using .T (shape {transposed_row_vector.shape}):\n{transposed_row_vector}")

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total number of bytes: 200 bytes

Original 1D array reshaped to a column vector (shape (25, 1)):
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using reshape() and .T (shape (1, 25)):
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]

Transpose of 1D array using .T (shape (25,)):
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75

### Q5. Create a 2-D Array of three rows and four columns, named `ucs420_<your_name>>` with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as `reshaped_ucs420_<your_name>>`. Resize the array to two rows and three columns and name it as `resized_ucs420_<your_name>>`.

In [7]:


ucs420_a = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print(f"Original 2D Array (ucs420_a):\n{ucs420_a}")

print(f"\nMean of the array: {np.mean(ucs420_a)}")
print(f"Median of the array: {np.median(ucs420_a)}")
print(f"Maximum element in the array: {np.max(ucs420_a)}")
print(f"Minimum element in the array: {np.min(ucs420_a)}")
print(f"Unique elements in the array: {np.unique(ucs420_a)}")

reshaped_ucs420_a = ucs420_a.reshape(4, 3)
print(f"\nReshaped array (4 rows, 3 columns):\n{reshaped_ucs420_a}")

resized_ucs420_a = np.resize(ucs420_a, (2, 3))
print(f"\nResized array (2 rows, 3 columns):\n{resized_ucs420_a}")

Original 2D Array (ucs420_a):
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean of the array: 43.333333333333336
Median of the array: 37.5
Maximum element in the array: 90
Minimum element in the array: 10
Unique elements in the array: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped array (4 rows, 3 columns):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized array (2 rows, 3 columns):
[[10 20 30]
 [40 50 60]]
